/**
 * Generate reference-scored fixture values.
 *
 * Reads fixture definitions (hands + decks), runs the reference scorer on each,
 * and writes src/test/reference-fixtures.gen.ts with the computed expected values.
 *
 * Usage:
 *   bun run gen:ref
 *
 * When to run:
 *   - Once during initial setup
 *   - After changing game data (rp-cards.csv, rp-fusions1.csv)
 *   - After changing the reference scorer logic
 *   - After adding/editing fixture scenarios in reference-fixture-defs.ts
 *
 * The generated file is committed to the repo. Unit tests read from it directly.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import {
  type DeckFixtureDef,
  deckFixtureDefs,
  type HandFixtureDef,
  handFixtureDefs,
} from "../src/test/reference-fixture-defs";
import { referenceEvaluateHand, referenceScoreDeck } from "../src/test/reference-scorer";
import { createAllCardsBuffers } from "../src/test/test-helpers";

const buf = createAllCardsBuffers();
const { fusionTable, cardAtk } = buf;

// --- Score hand fixtures (instant) ---

console.log(`Scoring ${handFixtureDefs.length} hand fixtures...`);

const handResults: { def: HandFixtureDef; expectedMaxAtk: number }[] = [];
for (const def of handFixtureDefs) {
  const score = referenceEvaluateHand(def.hand, fusionTable, cardAtk);
  handResults.push({ def, expectedMaxAtk: score });
  console.log(`  ${score}  ${def.description}`);
}

// --- Score deck fixtures (slow: ~0.1-6s each) ---

console.log(`\nScoring ${deckFixtureDefs.length} deck fixtures...`);

const deckResults: { def: DeckFixtureDef; expectedAvgAtk: number }[] = [];
for (const def of deckFixtureDefs) {
  const start = performance.now();
  const score = referenceScoreDeck(def.deck, fusionTable, cardAtk);
  const elapsed = ((performance.now() - start) / 1000).toFixed(1);
  deckResults.push({ def, expectedAvgAtk: score });
  console.log(`  ${score.toFixed(2)}  ${def.description}  (${elapsed}s)`);
}

// --- Write generated file ---

const handEntries = handResults
  .map(
    ({ def, expectedMaxAtk }) =>
      `  { hand: ${JSON.stringify(def.hand)}, expectedMaxAtk: ${expectedMaxAtk}, description: ${JSON.stringify(def.description)} },`,
  )
  .join("\n");

const deckEntries = deckResults
  .map(
    ({ def, expectedAvgAtk }) =>
      `  { deck: ${JSON.stringify(def.deck)}, expectedAvgAtk: ${expectedAvgAtk}, description: ${JSON.stringify(def.description)} },`,
  )
  .join("\n");

const output = `/**
 * AUTO-GENERATED by: bun run gen:ref
 * DO NOT EDIT — edit reference-fixture-defs.ts instead, then regenerate.
 */

export interface HandFixture {
  hand: number[];
  expectedMaxAtk: number;
  description: string;
}

export interface DeckFixture {
  deck: number[];
  expectedAvgAtk: number;
  description: string;
}

export const handFixtures: HandFixture[] = [
${handEntries}
];

export const deckFixtures: DeckFixture[] = [
${deckEntries}
];
`;

const outPath = path.resolve(import.meta.dirname, "../src/test/reference-fixtures.gen.ts");
fs.writeFileSync(outPath, output);
console.log(`\nWrote ${outPath}`);
